using System;
using NUnit.Framework;
using Moq;
using MyCode;

namespace MyCode.Tests
{
    [TestFixture]
    public class MyClassTests
    {
        [Test]
        public void FirstMethodTestTest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void SecondMethodTestTest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void MethodWithParamTest()
        {
            string message = default(string); 

            Assert.Fail("autogenerated");
        }
    }
}