using NUnit.Framework;
using Moq;
using MyCode;

namespace MyCode.Tests
{
    [TestFixture]
    public class MyTestClass2Tests
    {
        private MyTestClass2 _myTestClass2UnderTest; 

        private Mock<IMyTestInterface> _interfaceParam; 

        [SetUp]
        public void SetUp()
        {
            _interfaceParam = new Mock<IMyTestInterface>;
            _myTestClass2UnderTest = new MyTestClass2(_interfaceParam.Object);
        }

        [Test]
        public void GetInterfaceTest()
        {
            IMyTestInterface actual = _myTestClass2.GetInterface(); 

            IMyTestInterface expected = new Mock<IMyTestInterface>();
            Assert.AreEqual(_expected.Object, actual);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void SetInterfaceTest()
        {
            IMyTestInterface interfaceParam = new Mock<IMyTestInterface>(); 

            Assert.Fail("autogenerated");
        }
    }
}