using NUnit.Framework;
using Moq;
using MyCode;

namespace MyCode.Tests
{
    [TestFixture]
    public class MyTestClass1Tests
    {
        private MyTestClass1 _myTestClass1UnderTest; 

        private int _p1 = default(int);
        private double _p2 = default(double); 

        [SetUp]
        public void SetUp()
        {
            _myTestClass1UnderTest = new MyTestClass1(_p1, _p2);
        }

        [Test]
        public void GetNameTest()
        {
            string actual = _myTestClass1.GetName(); 

            string expected = default(string);
            Assert.AreEqual(_expected, actual);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void DoSumTest()
        {
            double param1 = default(double);
            double param2 = default(double); 

            double actual = _myTestClass1.DoSum(_param1, _param2); 

            double expected = default(double);
            Assert.AreEqual(_expected, actual);
            Assert.Fail("autogenerated");
        }
    }
}